// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plkjqrbykmnqortgkqjv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsa2pxcmJ5a21ucW9ydGdrcWp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0OTYwNDQsImV4cCI6MjA3MDA3MjA0NH0.ErYGsyYud0pzZ0f5gELuRhx_Mt4vt8Q0UHaS1XFONEU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});